title: LLA Roborunners
email: hello@roborunners.org
github_username:  roborunners
twitter_username:  roborunners
description: >
  Loma Linda Academy's FTC team, the 7092 Roborunners. We are a third-year FTC
  robotics team, based out of Loma Linda, California.
url: "http://roborunnners.org"
baseurl: ""

markdown: kramdown

exclude: ["README.md", "Gemfile", "Gemfile.lock"]
